=== uo289549/SEW/xml/rutas.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/rutas" elementFormDefault="qualified" targetNamespace="http://tempuri.org/rutas" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tipo" />
				<xs:element ref="medioTransporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fechaInicio" />
				<xs:element minOccurs="0" maxOccurs="1" ref="horaInicio" />
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="personasAdecuadas" />
				<xs:element ref="lugarInicio" />
				<xs:element ref="direccionInicio" />
				<xs:element ref="coordenadas" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />
	<xs:element name="tipo" type="xs:string" />
	<xs:element name="medioTransporte" type="xs:string" />
	<xs:element name="fechaInicio" type="xs:date" />
	<xs:element name="horaInicio" type="xs:dateTime" />
	<xs:element name="duracion" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="personasAdecuadas" type="xs:string" />
	<xs:element name="lugarInicio" type="xs:string" />
	<xs:element name="direccionInicio" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="latitud" type="xs:float"/>
				<xs:element name="longitud" type="xs:float"/>
				<xs:element name="altitud" type="xs:float"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias" type="xs:string" />
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>


	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreHito" />
				<xs:element ref="descripcionHito" />
				<xs:element ref="coordenadasHito" />
				<xs:element ref="distanciaDesdeAnterior" />
				<xs:element minOccurs="1" maxOccurs="5" ref="galeriaFotografica" />
				<xs:element minOccurs="0" maxOccurs="3" ref="galeriaVideos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombreHito" type="xs:string" />
	<xs:element name="descripcionHito" type="xs:string" />
	<xs:element name="coordenadasHito">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="latitud" type="xs:float"/>
				<xs:element name="longitud" type="xs:float"/>
				<xs:element name="altitud" type="xs:float"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distanciaDesdeAnterior">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="galeriaFotografica" type="xs:string" />
	<xs:element name="galeriaVideos" type="xs:string" />
</xs:schema>

=== uo289549/SEW/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta>
        <nombre>Ulsanbawi Rock</nombre>
        <tipo>Senderismo</tipo>
        <medioTransporte>A pie</medioTransporte>
        <duracion>PT3H30M</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Caminata de 3,8km, unas tres horas y media ida y vuelta, con un ascenso a la roca Ulsanbawi para finalizar, desde la que vamos a tener unas vistas increíbles.</descripcion>
        <personasAdecuadas>Personas en 
            buena forma física</personasAdecuadas>
        <lugarInicio>Seoraksan National Park</lugarInicio>
        <direccionInicio>Seoraksan National Park Seorak District, Seorak-dong, Sokcho-si, Gangwon-do, Corea del Sur</direccionInicio>
        <coordenadas>
            <latitud>38.172477</latitud>
            <longitud>128.494068</longitud>
            <altitud>199.64</altitud>
        </coordenadas>
        <referencias>https://www.tripadvisor.es/Attraction_Review-g317129-d3808309-Reviews-Ulsanbawi_Rock-Sokcho_Gangwon_do.html</referencias>
        <referencias>https://en.wikipedia.org/wiki/Ulsanbawi</referencias>
        <referencias>https://es.wikiloc.com/rutas-senderismo/seoraksan-national-park-dir-ulsanbawi-rock-62983271</referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Llegar a mirador</nombreHito>
                <descripcionHito>Llegar al mirador de las escaleras</descripcionHito>
                <coordenadasHito>
                    <latitud>38.192007</latitud>
                    <longitud>128.472880</longitud>
                    <altitud>523.07</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">3.2</distanciaDesdeAnterior>
                <galeriaFotografica>mirador.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Llegar a la cima</nombreHito>
                <descripcionHito>llegar a la cima de la roca</descripcionHito>
                <coordenadasHito>
                    <latitud>38.193271</latitud>
                    <longitud>128.475824</longitud>
                    <altitud>634.73</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">1.5</distanciaDesdeAnterior>
                <galeriaFotografica>rocaUlsanbawi.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Heundeul Bawi Rock</nombreHito>
                <descripcionHito>Templo de la zona</descripcionHito>
                <coordenadasHito>
                    <latitud>38.189925</latitud>
                    <longitud>128.474997</longitud>
                    <altitud>451.5</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">3</distanciaDesdeAnterior>
                <galeriaFotografica>templo.jpg</galeriaFotografica>
            </hito>
        </hitos>
    </ruta>

    <ruta>
        <nombre>Visita turística por la ciudad de Seúl</nombre>
        <tipo>Arquitectura y monumentos</tipo>
        <medioTransporte>A pie</medioTransporte>
        <duracion>PT8H</duracion>
        <agencia>Tripadvisor</agencia>
        <descripcion>Este recorrido turístico de día completo por Seúl muestra lo mejor de la historia, cultura y tradiciones de Corea. Dirigido por un guía, vea los principales lugares de interés de la ciudad, incluidos el Templo Jogyesa y el Palacio Gyeongbokgung, el Museo Nacional Folclórico, la Torre N de Seúl y la aldea Namsangol Hanok. Observe el cambio de guardia durante una parada en la puerta de Gwanghwamun y disfrute de un almuerzo tradicional coreano con sus compañeros de viaje en Insadong. Su recorrido de día completo también incluye una parada en un centro tradicional de ginseng</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Templo budista de Jogyesa</lugarInicio>
        <direccionInicio>55 Ujeongguk-ro, Jongno-gu, Seoul, Corea del Sur</direccionInicio>
        <coordenadas>
            <latitud>37.573904</latitud>
            <longitud>126.982596</longitud>
            <altitud>30.38</altitud>
        </coordenadas>
        <referencias>https://www.tripadvisor.es/AttractionProductReview-g294197-d11454649-Seoul_City_Sightseeing_Tour_Including_Gyeongbokgung_Palace_N_Seoul_Tower_and_Namsa.html</referencias>
        <referencias>https://es.wikipedia.org/wiki/Gyeongbokgung</referencias>
        <referencias>http://www.jogyesa.kr/</referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Palacio de Gyeongbokgung</nombreHito>
                <descripcionHito>Llegar al palacio de Gyeongbokgung</descripcionHito>
                <coordenadasHito>
                    <latitud>37.579522</latitud>
                    <longitud>126.977054</longitud>
                    <altitud>36.46</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">1.1</distanciaDesdeAnterior>
                <galeriaFotografica>PalacioGyeongbokgung.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Torre de Seúl</nombreHito>
                <descripcionHito>Llegar a la torre de Seul</descripcionHito>
                <coordenadasHito>
                    <latitud>37.551123</latitud>
                    <longitud>126.988255</longitud>
                    <altitud>246.94</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">3</distanciaDesdeAnterior>
                <galeriaFotografica>torreSeul.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Namsangol Hanok Village</nombreHito>
                <descripcionHito>Llegar al Namsangol Hanok Village</descripcionHito>
                <coordenadasHito>
                    <latitud>37.559267</latitud>
                    <longitud>126.994470</longitud>
                    <altitud>43.96</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">2.6</distanciaDesdeAnterior>
                <galeriaFotografica>NamsangolHanokVillage.jpg</galeriaFotografica>
            </hito>
        </hitos>
    </ruta>

    <ruta>
        <nombre>Tour de Busan</nombre>
        <tipo>Mixta Arquitectura y paisajística</tipo>
        <medioTransporte>A pie</medioTransporte>
        <duracion>PT9H</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Recorrido turístico por la ciudad de Busan que incluye visitas a atracciones destacadas como el mercado de pescado de Jagalchi, el templo Haedong Yonggungsa y la aldea cultural de Gamcheon</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Estación de tren de Busan </lugarInicio>
        <direccionInicio>Jungang-daero, 초량제3동 Dong-gu, Busan, Corea del Sur</direccionInicio>
        <coordenadas>
            <latitud>35.115225</latitud>
            <longitud>129.041804</longitud>
            <altitud>9.07</altitud>
        </coordenadas>
        <referencias>https://www.tripadvisor.es/AttractionProductReview-g297884-d23829444-Small_Group_Full_Day_Busan_Tour_Max_6_Pax-Busan.html</referencias>
        <referencias>https://es.wikipedia.org/wiki/Busan</referencias>
        <referencias>https://mochilerosdospuntocero.com/asia/corea/busan-que-ver-hacer/</referencias>
        <recomendacion>7</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Haedong Yonggungsa</nombreHito>
                <descripcionHito>Llegar al templo Haedong Yonggungsa</descripcionHito>
                <coordenadasHito>
                    <latitud>35.188357</latitud>
                    <longitud>129.223388</longitud>
                    <altitud>12.70</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">23.4</distanciaDesdeAnterior>
                <galeriaFotografica>haedongYonggungsa.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Aldea cultural de Gamcheon</nombreHito>
                <descripcionHito>Pasear por las calles de Gamcheon</descripcionHito>
                <coordenadasHito>
                    <latitud>35.097357</latitud>
                    <longitud>129.010574</longitud>
                    <altitud>146.42</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">21.8</distanciaDesdeAnterior>
                <galeriaFotografica>gamcheon.jpg</galeriaFotografica>
            </hito>
            <hito>
                <nombreHito>Songdo Skywalk</nombreHito>
                <descripcionHito>Pasear por el puente de Songdo Skywalk</descripcionHito>
                <coordenadasHito>
                    <latitud>35.075993</latitud>
                    <longitud>129.021556</longitud>
                    <altitud>3.53</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidades="kilometros">4</distanciaDesdeAnterior>
                <galeriaFotografica>songdoSkywalk.jpg</galeriaFotografica>
            </hito>
        </hitos>
    </ruta>
</rutas>
